### ISSUE TITLE
Création du compte

### ISSUE THREAD

**Issue by jrouet** [ADcreatif/wardieval#4]
Plusieurs propositions :
- Rendre plus difficile le multi-compte en comparant l'IP à la création du compte
- Demander une adresse email avec envoie d'un lien d'activation à cet email pour la création d'un compte
- Mettre en place un système de captcha pour éviter le spam

**Comment by ADcreatif** [comment]
Je n'ai pas prévu d'interdire le multi compte. 
- ça reste RP
- il y a (aura) un légère perte de ressources pour les attaques. 
- les échanges n'étant pas possible
