### ISSUE TITLE
Dev Notes sur Page d'accueil

### ISSUE THREAD

**Issue by jrouet** [ADcreatif/wardieval#5]
Idée :
Utiliser la page d'accueil pour y mettre des notes qui expliquent les maj. Sous la forme de mcupdate ?
http://mcupdate.tumblr.com/

**Comment by ADcreatif** [comment]
avec une mise à jour tous les 6 mois, ce dev est secondaire ^^
J'ai à long terme envie d'ajouter un petit blog

**Comment by ADcreatif** [comment]
Fait !
